<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\Matt\Desktop\YetAnotherSudokuPlayer\YetAnotherSudokuPlayer.nunit" total="1" failures="1" not-run="0" date="2009-03-28" time="19:08:18">
  <environment nunit-version="2.4.8.0" clr-version="2.0.50727.3053" os-version="Microsoft Windows NT 6.0.6001 Service Pack 1" platform="Win32NT" cwd="C:\Users\Matt\Desktop\YetAnotherSudokuPlayer" machine-name="LT-MLENARZ" user="Matt" user-domain="LT-MLENARZ" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite name="C:\Users\Matt\Desktop\YetAnotherSudokuPlayer\YetAnotherSudokuPlayer.nunit" success="False" time="2.326" asserts="0">
    <results>
      <test-suite name="C:\Users\Matt\Desktop\YetAnotherSudokuPlayer\YetAnotherSudokuPlayer.Tests\bin\Debug\YetAnotherSudokuPlayer.Tests.exe" success="False" time="2.323" asserts="0">
        <results>
          <test-suite name="YetAnotherSudokuPlayer" success="False" time="2.323" asserts="0">
            <results>
              <test-suite name="Tests" success="False" time="2.323" asserts="0">
                <results>
                  <test-suite name="Tests" success="False" time="2.322" asserts="0">
                    <results>
                      <test-suite name="SolverTests" success="False" time="2.302" asserts="0">
                        <results>
                          <test-case name="YetAnotherSudokuPlayer.Tests.Tests.SolverTests.SolveVeryHard2" executed="True" success="False" time="2.286" asserts="0">
                            <failure>
                              <message><![CDATA[Exception occured while solving board: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at YetAnotherSudokuPlayer.Components.SudokuBoard.SolveCore(BackgroundWorker bw, Boolean showSolution) in C:\Users\Matt\Desktop\YetAnotherSudokuPlayer\YetAnotherSudokuPlayer.Components\SudokuBoard.cs:line 619
   at YetAnotherSudokuPlayer.Components.SudokuBoard.Solve() in C:\Users\Matt\Desktop\YetAnotherSudokuPlayer\YetAnotherSudokuPlayer.Components\SudokuBoard.cs:line 151
   at YetAnotherSudokuPlayer.Tests.Tests.SolverTests.SolveVeryHard2() in C:\Users\Matt\Desktop\YetAnotherSudokuPlayer\YetAnotherSudokuPlayer.Tests\Tests\SolverTests.cs:line 207]]></message>
                              <stack-trace><![CDATA[at YetAnotherSudokuPlayer.Tests.Tests.SolverTests.SolveVeryHard2() in C:\Users\Matt\Desktop\YetAnotherSudokuPlayer\YetAnotherSudokuPlayer.Tests\Tests\SolverTests.cs:line 211
]]></stack-trace>
                            </failure>
                          </test-case>
                        </results>
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>